http_path = "/"
css_dir = "../css"
sass_dir = "../scss"
images_dir = "../images"
javascripts_dir = "../js"
# output_style = :compressed
output_style = :nested
relative_assets=true
line_comments = false
sourcemap = true